%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: \\LONGBEACH\Aaron\Documents\Pace\CS655\myNet\Epson-Parts-By-Month-2006-2017.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/12/04 23:40:04

%% Import the data
[~, ~, raw] = xlsread('Epson-Parts-By-Month-2006-2017.xlsx','Sheet1','B2:EM674');

%% Replace non-numeric cells with 0.0
R = cellfun(@(x) (~isnumeric(x) && ~islogical(x)) || isnan(x),raw); % Find non-numeric cells
raw(R) = {0.0}; % Replace non-numeric cells

%% Create output variable
importData = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw R;